[package]
org = "ballerina_exercism"
name = "database_employee_onboarding"
version = "0.1.0"
distribution = "2201.5.0"

[[platform.java11.dependency]]
artifactId = "h2"
version = "2.0.206"
groupId = "com.h2database"
